export { default as MyContainer } from "./MyContainer/MyContainer";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Dishes } from "./Dishes/Dishes";
export { default as Footer } from "./Footer/Footer";
export { default as MyCard } from "./MyCard/MyCard";
export { default as Serene } from "./Serene/Serene";
export { default as SelectedCard } from "./SelectedCard/SelectedCard";
